from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

from src.ui import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(862, 692)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        MainWindow.setMaximumSize(QSize(90000, 900000))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.verticalSpacer = QSpacerItem(20, 9, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_2.addItem(self.verticalSpacer, 0, 1, 1, 1)

        self.horizontalSpacer = QSpacerItem(131, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer, 1, 0, 1, 1)

        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        self.boardImage = QWidget(self.centralwidget)
        self.boardImage.setObjectName(u"boardImage")
        self.boardImage.setMinimumSize(QSize(500, 500))
        self.boardImage.setMaximumSize(QSize(500, 500))
        self.boardImage.setStyleSheet(u"#boardImage{\n"
"	image: url(:/images/board.jpg);\n"
"}\n"
"\n"
"#boardImage QPushButton{\n"
"	background-color: rgb(52, 101, 164);\n"
"	border-radius: 20px\n"
"}\n"
"\n"
"#boardImage QPushButton:hover{\n"
"	background-color: rgb(32, 81, 144);\n"
"}\n"
"")
        self.button3 = QPushButton(self.boardImage)
        self.button3.setObjectName(u"button3")
        self.button3.setGeometry(QRect(70, 70, 40, 40))
        self.button3.setMinimumSize(QSize(40, 40))
        self.button3.setMaximumSize(QSize(40, 40))
        self.button4 = QPushButton(self.boardImage)
        self.button4.setObjectName(u"button4")
        self.button4.setGeometry(QRect(230, 70, 40, 40))
        self.button4.setMinimumSize(QSize(40, 40))
        self.button4.setMaximumSize(QSize(40, 40))
        self.button5 = QPushButton(self.boardImage)
        self.button5.setObjectName(u"button5")
        self.button5.setGeometry(QRect(390, 70, 40, 40))
        self.button5.setMinimumSize(QSize(40, 40))
        self.button5.setMaximumSize(QSize(40, 40))
        self.button10 = QPushButton(self.boardImage)
        self.button10.setObjectName(u"button10")
        self.button10.setGeometry(QRect(70, 230, 40, 40))
        self.button10.setMinimumSize(QSize(40, 40))
        self.button10.setMaximumSize(QSize(40, 40))
        self.button18 = QPushButton(self.boardImage)
        self.button18.setObjectName(u"button18")
        self.button18.setGeometry(QRect(70, 390, 40, 40))
        self.button18.setMinimumSize(QSize(40, 40))
        self.button18.setMaximumSize(QSize(40, 40))
        self.button19 = QPushButton(self.boardImage)
        self.button19.setObjectName(u"button19")
        self.button19.setGeometry(QRect(230, 390, 40, 40))
        self.button19.setMinimumSize(QSize(40, 40))
        self.button19.setMaximumSize(QSize(40, 40))
        self.button20 = QPushButton(self.boardImage)
        self.button20.setObjectName(u"button20")
        self.button20.setGeometry(QRect(390, 390, 40, 40))
        self.button20.setMinimumSize(QSize(40, 40))
        self.button20.setMaximumSize(QSize(40, 40))
        self.button13 = QPushButton(self.boardImage)
        self.button13.setObjectName(u"button13")
        self.button13.setGeometry(QRect(390, 230, 40, 40))
        self.button13.setMinimumSize(QSize(40, 40))
        self.button13.setMaximumSize(QSize(40, 40))
        self.button6 = QPushButton(self.boardImage)
        self.button6.setObjectName(u"button6")
        self.button6.setGeometry(QRect(120, 120, 40, 40))
        self.button6.setMinimumSize(QSize(40, 40))
        self.button6.setMaximumSize(QSize(40, 40))
        self.button8 = QPushButton(self.boardImage)
        self.button8.setObjectName(u"button8")
        self.button8.setGeometry(QRect(340, 120, 40, 40))
        self.button8.setMinimumSize(QSize(40, 40))
        self.button8.setMaximumSize(QSize(40, 40))
        self.button7 = QPushButton(self.boardImage)
        self.button7.setObjectName(u"button7")
        self.button7.setGeometry(QRect(230, 120, 40, 40))
        self.button7.setMinimumSize(QSize(40, 40))
        self.button7.setMaximumSize(QSize(40, 40))
        self.button16 = QPushButton(self.boardImage)
        self.button16.setObjectName(u"button16")
        self.button16.setGeometry(QRect(230, 340, 40, 40))
        self.button16.setMinimumSize(QSize(40, 40))
        self.button16.setMaximumSize(QSize(40, 40))
        self.button15 = QPushButton(self.boardImage)
        self.button15.setObjectName(u"button15")
        self.button15.setGeometry(QRect(120, 340, 40, 40))
        self.button15.setMinimumSize(QSize(40, 40))
        self.button15.setMaximumSize(QSize(40, 40))
        self.button17 = QPushButton(self.boardImage)
        self.button17.setObjectName(u"button17")
        self.button17.setGeometry(QRect(340, 340, 40, 40))
        self.button17.setMinimumSize(QSize(40, 40))
        self.button17.setMaximumSize(QSize(40, 40))
        self.button11 = QPushButton(self.boardImage)
        self.button11.setObjectName(u"button11")
        self.button11.setGeometry(QRect(120, 230, 40, 40))
        self.button11.setMinimumSize(QSize(40, 40))
        self.button11.setMaximumSize(QSize(40, 40))
        self.button12 = QPushButton(self.boardImage)
        self.button12.setObjectName(u"button12")
        self.button12.setGeometry(QRect(340, 230, 40, 40))
        self.button12.setMinimumSize(QSize(40, 40))
        self.button12.setMaximumSize(QSize(40, 40))
        self.button0 = QPushButton(self.boardImage)
        self.button0.setObjectName(u"button0")
        self.button0.setEnabled(True)
        self.button0.setGeometry(QRect(20, 20, 40, 40))
        self.button0.setMinimumSize(QSize(40, 40))
        self.button0.setMaximumSize(QSize(40, 40))
        self.button23 = QPushButton(self.boardImage)
        self.button23.setObjectName(u"button23")
        self.button23.setGeometry(QRect(440, 440, 40, 40))
        self.button23.setMinimumSize(QSize(40, 40))
        self.button23.setMaximumSize(QSize(40, 40))
        self.button1 = QPushButton(self.boardImage)
        self.button1.setObjectName(u"button1")
        self.button1.setGeometry(QRect(230, 20, 40, 40))
        self.button1.setMinimumSize(QSize(40, 40))
        self.button1.setMaximumSize(QSize(40, 40))
        self.button2 = QPushButton(self.boardImage)
        self.button2.setObjectName(u"button2")
        self.button2.setGeometry(QRect(440, 20, 40, 40))
        self.button2.setMinimumSize(QSize(40, 40))
        self.button2.setMaximumSize(QSize(40, 40))
        self.button22 = QPushButton(self.boardImage)
        self.button22.setObjectName(u"button22")
        self.button22.setGeometry(QRect(230, 440, 40, 40))
        self.button22.setMinimumSize(QSize(40, 40))
        self.button22.setMaximumSize(QSize(40, 40))
        self.button21 = QPushButton(self.boardImage)
        self.button21.setObjectName(u"button21")
        self.button21.setGeometry(QRect(20, 440, 40, 40))
        self.button21.setMinimumSize(QSize(40, 40))
        self.button21.setMaximumSize(QSize(40, 40))
        self.button9 = QPushButton(self.boardImage)
        self.button9.setObjectName(u"button9")
        self.button9.setGeometry(QRect(20, 230, 40, 40))
        self.button9.setMinimumSize(QSize(40, 40))
        self.button9.setMaximumSize(QSize(40, 40))
        self.button14 = QPushButton(self.boardImage)
        self.button14.setObjectName(u"button14")
        self.button14.setGeometry(QRect(440, 230, 40, 40))
        self.button14.setMinimumSize(QSize(40, 40))
        self.button14.setMaximumSize(QSize(40, 40))

        self.gridLayout.addWidget(self.boardImage, 0, 0, 1, 1)


        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)

        self.horizontalSpacer_2 = QSpacerItem(131, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer_2, 1, 2, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 9, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_2.addItem(self.verticalSpacer_2, 2, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 862, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.button3.setText("")
        self.button4.setText("")
        self.button5.setText("")
        self.button10.setText("")
        self.button18.setText("")
        self.button19.setText("")
        self.button20.setText("")
        self.button13.setText("")
        self.button6.setText("")
        self.button8.setText("")
        self.button7.setText("")
        self.button16.setText("")
        self.button15.setText("")
        self.button17.setText("")
        self.button11.setText("")
        self.button12.setText("")
        self.button0.setText("")
        self.button23.setText("")
        self.button1.setText("")
        self.button2.setText("")
        self.button22.setText("")
        self.button21.setText("")
        self.button9.setText("")
        self.button14.setText("")
    # retranslateUi

