USE [Triathlon]

-- setup
    -- initially
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    -- solution
    SET TRANSACTION ISOLATION LEVEL READ COMMITTED

-- act
BEGIN TRANSACTION
SELECT * FROM Athletes
WAITFOR DELAY '00:00:10'
SELECT * FROM Athletes
COMMIT TRANSACTION