USE [Triathlon]

-- setup
	-- initially
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED

	-- solution
	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

-- act
BEGIN TRAN
SELECT * FROM Athletes
WAITFOR DELAY '00:00:05'
SELECT * FROM Athletes
COMMIT TRAN